In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import cm
from datetime import date
import collections
import datetime
import os
import xarray as xr
from cycler import cycler
import matplotlib.patches as mpatches

In [2]:
scenarios = ['ssp126','ssp245','ssp370','ssp585']

modelnames = ['BCC-CSM2-MR', 'CESM2', 'CESM2-WACCM', 'EC-Earth3', 'EC-Earth3-Veg', 'FGOALS-f3-L', 'GFDL-ESM4', 
                  'INM-CM4-8', 'INM-CM5-0', 'MPI-ESM1-2-HR', 'MRI-ESM2-0', 'NorESM2-MM']

basins = {'RHINE':'6242', 'RHONE':'6243','PO':'6241', 'DANUBE':'6202', 'TITICACA':'3912', 'SANTA':'3425', 
            'OCONA':'3418', 'MAJES':'3416', 'MAGDALENA':'3227', 'AMAZON':'3203', 'YELCHO':'3429', 
            'VALDIVIA':'3428', 'SERRANO':'3426', 'RAPEL':'3423', 'PUELO':'3422', 'PASCUA':'3420', 
            'PALENA':'3419', 'HUASCO':'3412', 'COPIAPO':'3409', 'CISNES':'3408', 'BIOBIO':'3405', 'BAKER':'3404',
            'AZOPARDO':'3403', 'AISEN':'3401', 'SANTA CRUZ':'3244', 'NEGRO':'3232', 'COLORADO':'3212', 
            'CHICO':'3209', 'TORNEALVEN':'6255', 'THJORSA':'6254', 'OLFUSA':'6237', 'LULEALVEN':'6227', 
            'KUBAN':'6223', 'KALIXALVEN':'6219', 'GLOMAA':'6213', 'DRAMSELVA':'6209', 'SVARTA':'6110', 
            'LAGARFLJOT':'6104', 'JOKULSA A FJOLLUM':'6101', 'CLUTHA':'5406', 'YUKON':'4435', 'TAKU':'4431', 
             'SUSITNA':'4430','STIKINE':'4428', 'SKEENA':'4427','SKAGIT':'4426','NUSHAGAK':'4418','NASS':'4416',
            'KUSKOKWIM':'4414','FRASER':'4410', 'COPPER':'4408', 'COLUMBIA':'4406', 'ALSEK':'4401', 'NELSON':'4125', 
              'MACKENZIE':'4123','COLVILLE':'4110', 'YSYK-KOL':'2919', 'UVS NUUR':'2918', 'TARIM HE':'2914', 
              'TALAS':'2913', 'LAKE BALKHASH':'2910','HAR US NUUR':'2909', 'CHUY':'2905', 'ARAL SEA':'2902', 
              'YELLOW RIVER':'2434', 'MEKONG':'2421', 'KAMCHATKA':'2413', 'SALWEEN':'2319', 'IRRAWADDY':'2310', 
              'INDUS':'2309', 'GANGES':'2306','BRAHMAPUTRA':'2302', 'OB':'2108', 'INDIGIRKA':'2103', 'YANGTZE' : '2433'}

regions = ['RGI 01', 'RGI 02', 'RGI 06', 'RGI 08', 'RGI 10', 'RGI 11', 'RGI 12', 
           'RGI 13', 'RGI 15', 'RGI 16', 'RGI 17', 'RGI 18']

gmodels = ['GloGEM', 'OGGM', 'PyGEM']

fpath0 = '/Users/finnwimberly/Desktop/Lizz Research/CSV Outputs/'

In [3]:
# Create new index using pandas date_range function
start_date = datetime.date(2000, 1, 1)
end_date = datetime.date(2100, 12, 1)
new_indices = pd.date_range(start_date, end_date, freq='MS').strftime('%Y-%m').tolist()

In [4]:
#Importing runoff data
all_rf_data = {}
all_rf_data_annual = {}

for r, region in enumerate(regions):
    fpath = fpath0 + 'Runoff/' + region + '/'
    
    for s, SSP in enumerate(scenarios):
        if SSP not in all_rf_data:
            all_rf_data[SSP] = {}
            all_rf_data_annual[SSP] = {}
        
        for b, basin in enumerate(basins):
            if basin not in all_rf_data[SSP]:
                all_rf_data[SSP][basin] = {}
                all_rf_data_annual[SSP][basin] = {}
            
            for m, GCM in enumerate(modelnames):
                fname = f"runoff_{GCM}_{SSP}_{basin}.csv"
                file_path = os.path.join(fpath, fname)  # Construct the full file path

                if os.path.exists(file_path):
                    try:
                        temp_df = pd.read_csv(file_path, index_col=0)
                        temp_df.index = new_indices
                        temp_df.index = pd.to_datetime(new_indices)
                        
                        all_rf_data[SSP][basin][GCM] = temp_df
                        all_rf_data_annual[SSP][basin][GCM] = temp_df.resample('A').sum()
                    except FileNotFoundError:
                        continue

In [5]:
#Calculating our RMQ

all_rf_w_mean = {}
RMQ_annual = {}

for s, SSP in enumerate(scenarios):
    all_rf_w_mean[SSP] = {}
    RMQ_annual[SSP] = {}
    for b, basin in enumerate(basins):
        all_rf_w_mean[SSP][basin] = {}
        RMQ_annual[SSP][basin] = {}
        for m, GCM in enumerate(modelnames):
            original_df = all_rf_data_annual[SSP][basin][GCM]
            
            # Calculate the mean for each year across the models
            mean_df = original_df.mean(axis=1)
            mean_df = pd.DataFrame({'Mean': mean_df})

            #Creating a new concatenated df
            all_rf_w_mean[SSP][basin][GCM] = pd.concat([original_df, mean_df], axis = 1) 
            
            RMQ_df = original_df.divide(mean_df['Mean'], axis=0)
            RMQ_annual[SSP][basin][GCM] = RMQ_df

In [9]:
all_rf_w_mean[SSP][basin][GCM]

              GloGEM     PyGEM      OGGM      Mean
2000-12-31  3.042487  1.665514  4.598299  3.102100
2001-12-31  3.032454  2.171574  5.200988  3.468339
2002-12-31  3.060916  2.102881  5.318495  3.494097
2003-12-31  3.069172  2.800038  5.345780  3.738330
2004-12-31  2.885225  2.389525  5.148618  3.474456
...              ...       ...       ...       ...
2096-12-31  3.260244  1.881188  5.453897  3.531776
2097-12-31  2.829508  2.005611  5.675107  3.503409
2098-12-31  2.838724  1.819615  4.891775  3.183371
2099-12-31  2.879728  1.848195  5.505889  3.411271
2100-12-31  2.840810  1.927366  0.000000  1.589392

[101 rows x 4 columns]

In [10]:
RMQ_annual[SSP][basin][GCM]

              GloGEM     PyGEM      OGGM
2000-12-31  0.980783  0.536899  1.482318
2001-12-31  0.874325  0.626114  1.499562
2002-12-31  0.876025  0.601838  1.522137
2003-12-31  0.821001  0.749008  1.429992
2004-12-31  0.830411  0.687741  1.481849
...              ...       ...       ...
2096-12-31  0.923117  0.532646  1.544236
2097-12-31  0.807644  0.572474  1.619882
2098-12-31  0.891735  0.571600  1.536665
2099-12-31  0.844181  0.541791  1.614029
2100-12-31  1.787356  1.212644  0.000000

[101 rows x 3 columns]

In [28]:
# Initialize a dictionary to store median values
multi_GCM_median = {}

# Iterate through each SSP
for SSP, SSP_data in all_rf_data_annual.items():
    # Initialize a dictionary for the current SSP
    multi_GCM_median[SSP] = {}
    
    # Iterate through each basin
    for basin, basin_data in SSP_data.items():
        # Initialize lists to store median values for each glacier model
        OGGM_medians = []
        GloGEM_medians = []
        PyGEM_medians = []
        
        # Iterate through each GCM in the current basin
        for GCM_data in basin_data.values():
            # Append median values for each glacier model to the corresponding list
            OGGM_medians.append(GCM_data['OGGM'])
            GloGEM_medians.append(GCM_data['GloGEM'])
            PyGEM_medians.append(GCM_data['PyGEM'])
        
        # Calculate the median for each glacier model across all GCMs in the current basin
        median_values = {
            'OGGM': pd.concat(OGGM_medians, axis=1).median(axis=1),
            'GloGEM': pd.concat(GloGEM_medians, axis=1).median(axis=1),
            'PyGEM': pd.concat(PyGEM_medians, axis=1).median(axis=1)
        }
        
        # Store the median values DataFrame in the dictionary
        multi_GCM_median[SSP][basin] = pd.DataFrame(median_values)

In [34]:
#Lets calculate the ratio between the largest and smallest average annual rf values
# Initialize a dictionary to store the ratio values
ratio_dict = {}
for SSP, SSP_data in multi_GCM_median.items():
    # Initialize a list to store the ratios for the current SSP
    ratios = []
    for basin, basin_data in SSP_data.items():
        # Calculate the mean annual runoff values for each glacier model
        mean_values = basin_data.mean(axis=0)
        
        # Select the largest and smallest mean values
        largest_mean = mean_values.max()
        smallest_mean = mean_values.min()
        
        # Calculate the ratio between the largest and smallest mean values
        ratio = largest_mean / smallest_mean
        
        # Append the ratio to the list
        ratios.append(ratio)
    
    # Create a Series with the ratios and set basins as index
    ratio_series = pd.Series(ratios, index=SSP_data.keys())
    
    # Store the Series in the dictionary
    ratio_dict[SSP] = ratio_series

# Create a DataFrame from the dictionary
ratio_df = pd.DataFrame(ratio_dict)

In [40]:
ratio_df['ssp245']['GANGES']

3.7852900985025735

In [6]:
basin_names = []
for basin, ID in basins.items():
    basin_names.append(basin)

RMQ = {}
for s, SSP in enumerate(scenarios):
    RMQ[SSP] = {}
    for m, GCM in enumerate(modelnames):
        RMQ_list = []  # List to store averages for each basin
        for b, basin in enumerate(basins):
            # Get the RMQ DataFrame for the current SSP, GCM, and basin
            rmq_df = RMQ_annual[SSP][basin][GCM]
            

            # Calculate the average of annual values for the current basin
            basin_average = rmq_df.mean()
            RMQ_list.append(basin_average)
            
        
        # Store the average values for the current SSP and GCM combination
        RMQ[SSP][GCM] = pd.DataFrame(RMQ_list)
        RMQ[SSP][GCM].index = basin_names

In [27]:
out_df = {}
for s, SSP in enumerate(scenarios):
    out_df[SSP] = {}
    for m, GCM in enumerate(modelnames):
        glo_values = RMQ[SSP][GCM]['GloGEM']
        oggm_values = RMQ[SSP][GCM]['OGGM']
        pygem_values = RMQ[SSP][GCM]['PyGEM']
        

        # Create a dictionary with values for the current basin
        data = {
            'GloGEM': glo_values,
            'OGGM': oggm_values,
            'PyGEM': pygem_values,
        }
                    
        # Create a DataFrame from the list of basin data
        out_df[SSP][GCM] = pd.DataFrame(data)  # Set the index as 'Basin'

In [30]:
output_dir = '/Users/finnwimberly/Desktop/Lizz Research/CSV Outputs/RMQ/'

for SSP in out_df:
    for GCM in out_df[SSP]:
        fname = f"RMQ{GCM}_{SSP}.csv"

        # Define the full path of the output file
        output_path = os.path.join(output_dir, fname)

        # Save the DataFrame as CSV
        out_df[SSP][GCM].to_csv(output_path, header=True, index=True)

In [7]:
all_rf_w_mean[SSP][basin][GCM]

              GloGEM     PyGEM      OGGM      Mean
2000-12-31  3.042487  1.665514  4.598299  3.102100
2001-12-31  3.032454  2.171574  5.200988  3.468339
2002-12-31  3.060916  2.102881  5.318495  3.494097
2003-12-31  3.069172  2.800038  5.345780  3.738330
2004-12-31  2.885225  2.389525  5.148618  3.474456
...              ...       ...       ...       ...
2096-12-31  3.260244  1.881188  5.453897  3.531776
2097-12-31  2.829508  2.005611  5.675107  3.503409
2098-12-31  2.838724  1.819615  4.891775  3.183371
2099-12-31  2.879728  1.848195  5.505889  3.411271
2100-12-31  2.840810  1.927366  0.000000  1.589392

[101 rows x 4 columns]

Calculating mean rf from historical period:

In [18]:
#Calculating the historical mean
RF_hist_mean = {}

for s, SSP in enumerate(scenarios):
    RF_hist_mean[SSP] = {}
    for b, basin in enumerate(basins):
        RF_hist_mean[SSP][basin] = {}
        for m, GCM in enumerate(modelnames):
            RF_hist_mean[SSP][basin][GCM] = all_rf_data_annual[SSP][basin][GCM][0:20].mean()

In [19]:
basin_names = []
for basin, ID in basins.items():
    basin_names.append(basin)

RF_hist = {}
for s, SSP in enumerate(scenarios):
    RF_hist[SSP] = {}
    for m, GCM in enumerate(modelnames):
        mean_list = []  # List to store values for each basin
        for b, basin in enumerate(basins):
            mean_values = RF_hist_mean[SSP][basin][GCM]
            mean_list.append(mean_values)
            
        
        # Store the average values for the current SSP and GCM combination
        RF_hist[SSP][GCM] = pd.DataFrame(mean_list)
        RF_hist[SSP][GCM].index = basin_names

In [20]:
out_df = {}
for s, SSP in enumerate(scenarios):
    out_df[SSP] = {}
    for m, GCM in enumerate(modelnames):
        glo_values = RF_hist[SSP][GCM]['GloGEM']
        oggm_values = RF_hist[SSP][GCM]['OGGM']
        pygem_values = RF_hist[SSP][GCM]['PyGEM']
        

        # Create a dictionary with values for the current basin
        data = {
            'GloGEM': glo_values,
            'OGGM': oggm_values,
            'PyGEM': pygem_values,
        }
                    
        # Create a DataFrame from the list of basin data
        out_df[SSP][GCM] = pd.DataFrame(data)  # Set the index as 'Basin'

In [21]:
output_dir = '/Users/finnwimberly/Desktop/Lizz Research/CSV Outputs/RF Historical Means/'

for SSP in out_df:
    for GCM in out_df[SSP]:
        fname = f"RF_hist_mean{GCM}_{SSP}.csv"

        # Define the full path of the output file
        output_path = os.path.join(output_dir, fname)

        # Save the DataFrame as CSV
        out_df[SSP][GCM].to_csv(output_path, header=True, index=True)

Calculating mean rf across the entire period:

In [46]:
#Calculating the historical mean
RF_mean = {}

for s, SSP in enumerate(scenarios):
    RF_mean[SSP] = {}
    for b, basin in enumerate(basins):
        RF_mean[SSP][basin] = {}
        for m, GCM in enumerate(modelnames):
            RF_mean[SSP][basin][GCM] = all_rf_data_annual[SSP][basin][GCM][0:101].mean()

In [47]:
basin_names = []
for basin, ID in basins.items():
    basin_names.append(basin)

RF = {}
for s, SSP in enumerate(scenarios):
    RF[SSP] = {}
    for m, GCM in enumerate(modelnames):
        mean_list = []  # List to store values for each basin
        for b, basin in enumerate(basins):
            mean_values = RF_mean[SSP][basin][GCM]
            mean_list.append(mean_values)
            
        
        # Store the average values for the current SSP and GCM combination
        RF[SSP][GCM] = pd.DataFrame(mean_list)
        RF[SSP][GCM].index = basin_names

In [48]:
out_df = {}
for s, SSP in enumerate(scenarios):
    out_df[SSP] = {}
    for m, GCM in enumerate(modelnames):
        glo_values = RF[SSP][GCM]['GloGEM']
        oggm_values = RF[SSP][GCM]['OGGM']
        pygem_values = RF[SSP][GCM]['PyGEM']
        

        # Create a dictionary with values for the current basin
        data = {
            'GloGEM': glo_values,
            'OGGM': oggm_values,
            'PyGEM': pygem_values,
        }
                    
        # Create a DataFrame from the list of basin data
        out_df[SSP][GCM] = pd.DataFrame(data)  # Set the index as 'Basin'

In [49]:
output_dir = '/Users/finnwimberly/Desktop/Lizz Research/CSV Outputs/RF Means/'

for SSP in out_df:
    for GCM in out_df[SSP]:
        fname = f"RF_mean{GCM}_{SSP}.csv"

        # Define the full path of the output file
        output_path = os.path.join(output_dir, fname)

        # Save the DataFrame as CSV
        out_df[SSP][GCM].to_csv(output_path, header=True, index=True)